FORMAT: 1A
HOST: https://zoeaeen13.github.io

# 美食家的口袋名單 Pocket list of Foodie

最齊全的美食平台，提供你最美味的餐廳選擇，可以查看所有的餐廳資料、回傳特定餐廳資料、刪除餐廳、新增餐廳、更改餐廳


## 查看所有餐廳 [/restaurants?location=台東市&type=1&limit=2]

- limit 為每頁前端希望顯示的資料數量, 若不帶預設顯示 25 筆

- location 為尋找的餐廳地點，例如台南市

- type 欄位為選擇的餐廳類型，日式、熱炒、宵夜等等

### 查看所有餐廳 [GET]

+ Response 200 (application/json)

    + Headers

    + Body

            {
                "restaurants": [
                    {
                        "id": 24,
                        "name": "福井日本料理",
                        "score": "4.3",
                        "likes": 27,
                        "address": "950台東縣台東市長沙街92號",
                        "open": true,
                        "website": "https://www.facebook.com/141315755928342/posts/2787811387945419/?d=n",
                        "contact": "+88689334038",
                        "comments": {
                            "total": 2,
                            "list": [
                            {
                                "name": "胖胖",
                                "content": "推薦炙燒鮭魚，牛肉串燒，炸豬排，蛤蜊鮮湯。吃的到老師傅的手藝，不錯吃。",
                                "score": 4.0,
                                "date": "2019_03_16"
                            },
                            {
                                "name": "WenYu Liao",
                                "content": "餐廳服務真的很好，因為行程稍微delay，店家還是很熱心的幫我們指揮停車，餐點全都好吃，用餐環境寬敞舒適。炸蝦採用草蝦，雖然小貴但份量紮實。鮭魚炒飯也夠水準。握手司份量大小適中，非常完美。已經期待下次二訪。",
                                "score": 4.5,
                                "date": "2020_12_07"
                            }
                            ]
                        }
                    },
                    {
                        "id": 25,
                        "name": "咔棒日式漁場料理",
                        "score": "4.3",
                        "likes": 114,
                        "address": "950台東縣台東市光明路261號",
                        "open": close,
                        "website": "https://www.ubereats.com/tw/taitung/food-delivery/%E5%92%94%E6%A3%92%E6%BC%81%E5%A0%B4%E6%97%A5%E5%BC%8F%E6%96%99%E7%90%86/wdoNbdnnRoqOaMHcTO0nJA?utm_source=google&utm_medium=organic&utm_campaign=place-action-link",
                        "contact": null,
                        "comments": {
                            "total": 1,
                            "list": [
                                {
                                    "name": "王秝汝",
                                    "content": "海鮮餐點新鮮好吃高CP值可惜熱湯很少!秋冬有海鮮火鍋應該更👍山葵章魚拌太鹹",
                                    "score": 4.2,
                                    "date": "2020_09_11"
                                }
                            ]
                        }
                    }
                ]
            }



## 查看單一餐廳資訊 [/restaurants/24]

在路徑填入餐廳 `{id}`，將回傳查詢的餐廳資訊

### 查看單一餐廳資訊 [GET]

+ Response 200 (application/json)

    + Headers

    + Body

            {
                "restaurants": [
                    {
                        "id": 24,
                        "name": "福井日本料理",
                        "score": "4.3",
                        "likes": 27,
                        "address": "950台東縣台東市長沙街92號",
                        "open": true,
                        "website": "https://www.facebook.com/141315755928342/posts/2787811387945419/?d=n",
                        "contact": "+88689334038",
                        "comments": {
                            "total": 2,
                            "list": [
                            {
                                "name": "胖胖",
                                "content": "推薦炙燒鮭魚，牛肉串燒，炸豬排，蛤蜊鮮湯。吃的到老師傅的手藝，不錯吃。",
                                "score": 4.0,
                                "date": "2019_03_16"
                            },
                            {
                                "name": "WenYu Liao",
                                "content": "餐廳服務真的很好，因為行程稍微delay，店家還是很熱心的幫我們指揮停車，餐點全都好吃，用餐環境寬敞舒適。炸蝦採用草蝦，雖然小貴但份量紮實。鮭魚炒飯也夠水準。握手司份量大小適中，非常完美。已經期待下次二訪。",
                                "score": 4.5,
                                "date": "2020_12_07"
                            }
                            ]
                        }
                    }
                ]
            }


## 新增餐廳資訊 [/restaurants]

如果有推薦的美食餐廳，歡迎新增名稱、地址及電話號碼，我們將納入資料庫

- name 餐廳名稱

- location 餐廳地址

- phone_number 餐廳電話

### 新增餐廳資訊 [POST]

+ Request  (application/json)

    + Headers

    + Body

            {
                "name": "蘭田手作日式豬排",
                "location": "台東縣台東市正氣北路 255 巷 14 號 6 號",
                "phone_number": "089345526",
            }

+ Response 200 (application/json)

    + Headers

    + Body

            {
                "result": true,
                "message": "ok",
                "data": [
                    {
                        "name": "蘭田手作日式豬排",
                        "location": "台東縣台東市正氣北路 255 巷 14 號 6 號",
                        "phone_number": "089345526",
                    }
                ]
            }

+ Response 400 (application/json)

    + Headers

    + Body

            {
                "result": false,
                "message": "Something is wrong",
                "data": []
            }

## 刪除餐廳資訊 [/restaurants/25]

如果餐廳已經移址或不存在，利用 DELETE 指令刪除該資訊，填入餐廳 `{id}`

### 刪除餐廳資訊 [DELETE]

+ Response 204


## 修改餐廳資訊 [/restaurants/2]

目前開放修改的資訊有餐廳名稱、地址更新及電話號碼

- name 更新餐廳名稱

- location 更新地址

- phone_number 更新餐廳的電話

### 修改餐廳資訊 [PATCH]

+ Request  (application/json)

    + Headers

    + Body

            {
                "name": "蘭田手作日式豬排",
                "location": "台東縣台東市正氣北路255巷14號6號",
                "phone_number": "089345526",
            }

+ Response 200 (application/json)

    + Headers

    + Body

            {
                "result": true,
                "message": "ok",
                "data": [
                    {
                        "name": "蘭田手作日式豬排",
                        "location": "台東縣台東市正氣北路255巷14號6號",
                        "phone_number": "089345526",
                        "updatedAt": "2020-07-26T07:44:27.242Z",
                    }
                ]
            }
